# Generated by Django 3.0.1 on 2020-01-17 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=35, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('source', models.CharField(default='unknown', max_length=50)),
                ('link', models.CharField(default='Not Applicable', max_length=100)),
                ('comments', models.CharField(blank=True, max_length=246, null=True)),
                ('IsActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Reward_Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reward_tier', models.PositiveIntegerField(default=0)),
                ('reward_claim_date', models.DateField(null=True)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadetApp.Cadet')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RewardApp.Reward')),
            ],
        ),
        migrations.CreateModel(
            name='Reward_Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reward_band', models.IntegerField(null=True)),
                ('required_hours', models.PositiveIntegerField(null=True)),
                ('rewards_list', models.ManyToManyField(blank=True, to='RewardApp.Reward')),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='required_points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RewardApp.Reward_Band'),
        ),
    ]
