# Generated by Django 3.0.1 on 2020-01-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0002_auto_20200101_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='IsActive',
            field=models.BooleanField(default=False),
        ),
    ]
