# Generated by Django 3.0.1 on 2020-01-01 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0003_reward_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='required_points',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_band',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
