# Generated by Django 3.0.1 on 2020-01-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0004_auto_20200101_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='required_points',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_band',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
