# Generated by Django 3.0.1 on 2020-01-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0007_auto_20200101_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='required_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_band',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
