# Generated by Django 3.0.1 on 2020-01-01 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0009_reward_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward_Band',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reward_band', models.IntegerField(max_length=3)),
                ('required_points', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reward',
            name='reward_band',
        ),
        migrations.AlterField(
            model_name='reward',
            name='required_points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RewardApp.Reward_Band'),
        ),
    ]
