# Generated by Django 3.0.1 on 2020-01-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0010_auto_20200101_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward_band',
            name='reward_band',
            field=models.IntegerField(null=True),
        ),
    ]
