# Generated by Django 3.0.1 on 2020-01-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0011_auto_20200101_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='comments',
            field=models.CharField(blank=True, max_length=246, null=True),
        ),
    ]
