# Generated by Django 3.0.1 on 2020-01-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0012_reward_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward_band',
            old_name='required_points',
            new_name='required_hours',
        ),
    ]
