# Generated by Django 3.0.1 on 2020-01-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0013_auto_20200101_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reward_log',
            name='reward_tier',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
