# Generated by Django 3.0.1 on 2020-01-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0014_user_reward_log_reward_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward_band',
            name='rewards_list',
            field=models.ManyToManyField(blank=True, to='RewardApp.Reward'),
        ),
    ]
