# Generated by Django 3.0.1 on 2020-01-03 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RewardApp', '0015_reward_band_rewards_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=35, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
