# Generated by Django 3.0.1 on 2020-01-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadet',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('years_since_joined', models.IntegerField(default=0)),
                ('bond_paid', models.DateField(blank=True, null=True)),
                ('joining_fee_paid', models.DateField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('total_duty_hours', models.IntegerField(default=0)),
                ('num_of_events', models.IntegerField(default=0)),
                ('training_hours', models.IntegerField(default=0)),
                ('other_hours', models.IntegerField(default=0)),
                ('meeting_hours', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
