# Generated by Django 3.0.1 on 2019-12-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadetApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadetsList',
            new_name='Cadet',
        ),
    ]
