# Generated by Django 3.0.1 on 2020-01-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadet',
            name='dems_id',
            field=models.IntegerField(default=0),
        ),
    ]
