# Generated by Django 3.0.1 on 2019-12-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadetApp', '0004_auto_20191225_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadet',
            old_name='name',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='cadet',
            old_name='id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='cadet',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadet',
            name='birthday',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cadet',
            name='bond_paid',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cadet',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cadet',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cadet',
            name='firstname',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='cadet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cadet',
            name='joining_fee_paid',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cadet',
            name='lastname',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='cadet',
            name='meeting_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadet',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadet',
            name='num_of_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadet',
            name='other_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadet',
            name='qualification',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='cadet',
            name='total_duty_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadet',
            name='training_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadet',
            name='years_since_joined',
            field=models.IntegerField(default=0),
        ),
    ]
