# Generated by Django 3.0.1 on 2019-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadetApp', '0008_auto_20191226_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='meeting_hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='mobile',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='num_of_events',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='other_hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='qualification',
            field=models.CharField(default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='rank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='total_duty_hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='training_hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='years_since_joined',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
