# Generated by Django 3.0.1 on 2020-01-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadetApp', '0010_auto_20191230_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='meeting_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='num_of_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='other_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='total_duty_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='training_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='years_since_joined',
            field=models.IntegerField(default=0),
        ),
    ]
