# Generated by Django 3.0.1 on 2019-12-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystemApp', '0002_auto_20191225_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadet',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='lastName',
        ),
    ]
