# Generated by Django 3.0.1 on 2019-12-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystemApp', '0003_auto_20191225_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
