# Generated by Django 3.0.1 on 2019-12-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystemApp', '0007_auto_20191226_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='bond_paid',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cadet',
            name='joining_fee_paid',
            field=models.DateField(null=True),
        ),
    ]
