# Generated by Django 3.0.1 on 2020-01-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CadetApp', '0001_initial'),
        ('RollMarkingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('details', models.TextField(max_length=100)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadetApp.Cadet')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RollMarkingApp.Meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadetApp.Cadet')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RollMarkingApp.Meeting')),
            ],
            options={
                'unique_together': {('meeting', 'cadet')},
            },
        ),
    ]
