# Generated by Django 2.2.5 on 2019-12-31 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadetApp', '0010_auto_20191230_1243'),
        ('RollMarkingApp', '0005_auto_20191229_2137'),
        ('FinancesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='TermFees',
            new_name='TermFee',
        ),
    ]
