# Generated by Django 2.2.5 on 2019-12-31 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RollMarkingApp', '0005_auto_20191229_2137'),
        ('CadetApp', '0010_auto_20191230_1243'),
        ('FinancesApp', '0002_auto_20191231_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='termfee',
            unique_together={('meeting', 'cadet')},
        ),
    ]
