# Generated by Django 2.2.5 on 2019-12-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadetApp', '0008_auto_20191226_0719'),
        ('RollMarkingApp', '0002_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='reason_code',
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(choices=[('E', 'Exams'), ('R', 'Religious Leave'), ('O', 'Other')], default='O', max_length=1)),
                ('cadet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CadetApp.Cadet')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RollMarkingApp.Meeting')),
            ],
        ),
    ]
