# Generated by Django 2.2.5 on 2019-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollMarkingApp', '0003_auto_20191228_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='reason_code',
            field=models.CharField(choices=[('u', 'Enexplained'), ('e', 'Exams'), ('r', 'Religious Leave'), ('o', 'Other')], default='O', max_length=1),
        ),
    ]
