# Generated by Django 2.2.5 on 2019-12-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RollMarkingApp', '0004_auto_20191229_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='reason_code',
            field=models.CharField(choices=[('u', 'Unexplained'), ('e', 'Exams'), ('r', 'Religious Leave'), ('o', 'Other')], default='o', max_length=1),
        ),
    ]
