# Generated by Django 2.2.5 on 2020-01-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadetApp', '0010_auto_20191230_1243'),
        ('RollMarkingApp', '0005_auto_20191229_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('meeting', 'cadet')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('meeting', 'cadet')},
        ),
    ]
